### ISSUE TITLE
Restore related Azure Functions to latest v2 runtime

### ISSUE THREAD

**Issue by antross** [webhintio/serverless-online-service#30]
To temporarily workaround an issue with the functions host not starting, I downgraded the `FUNCTIONS_EXTENSION_VERSION` app setting for our `service-functions-production` instance to `2.0.13019` instead of `~2`.

This should be restored to `~2` at some point after the next update (currently the latest is `2.0.13036`). See https://github.com/Azure/azure-functions-host/releases - looks like updates occur every few weeks or less. 

If the issue still persists after the next update, we should file a bug against the functions host to ensure it gets investigated.

**Comment by sarvaje** [comment]
Right now, production has the `FUNCTIONS_EXTENSION_VERSION` set to `~2` and it is working.
I think we can close this (for now hehehe)

**Comment by antross** [comment]
Yep, thanks for following up on this @sarvaje!
