### ISSUE TITLE
Determine if Linux Azure Functions can run workers

### ISSUE THREAD

**Issue by antross** [webhintio/serverless-online-service#4]
Mostly depends on if we can get a version of Chrome working.

**Comment by sarvaje** [comment]
We can run the worker only if we use a docker image. Closing this one and opening a [new issue](https://github.com/webhintio/serverless-online-service/issues/5) to track the implementation

**Comment by molant** [comment]
@sarvaje I think you forgot to close this issue so I'll do it but feel free to re-open if that's not the case.

**Comment by sarvaje** [comment]
🤦‍♂️
