### ISSUE TITLE
Script to create all the resources needed in Cloud providers

### ISSUE THREAD

**Issue by molant** [webhintio/serverless-online-service#7]
Similar to what we currently have in the online-service.

Look into https://www.terraform.io/ for this.

**Comment by molant** [comment]
@sarvaje you are working on this, right? I'll assign it to you but feel free to change anything if I've misunderstood

**Comment by sarvaje** [comment]
We already have a terraform script for azure (62528ec3e1eea06e1501b647e2f9a1c07e7d93c1). @molant is that enough to close this issue?

**Comment by molant** [comment]
I think so!
